spring:
  profiles:
    active: dev
  application:
    name: rupeexfer
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        jdbc:
          batch_versioned_data: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:h2:mem:rupeexfer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      leak-detection-threshold: 5000
      pool-name: rupeexfer-pool
      initialization-fail-timeout: 1
      validation-timeout: 5000

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration-ms: 86400000 # 24 hours

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.sanket.rupeexfer: DEBUG

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
